### ISSUE TITLE
webpack loader

### ISSUE THREAD

**Issue by Xiphe** [rtsao/styletron#108]
Wondering if there is a `styletron-loader` for webpack that allows me to keep my styles in a CSS file and apply them in a css-modules manner.

I found [cssobjects-loader](https://github.com/DoubleU23/cssobjects-loader) and [css-object-loader](https://github.com/pl12133/css-object-loader) but they both are not capable of handling pseudo classes and media-queries.

Do you know of something? If not, would you be interested in a contribution to this multi-package repo or should I maintain it on my own?

---

Here's what I'd like to do:

`Button.css`
```css
.button {
  font-size: 1.5em;
  color: fuchsia;
  @media screen and (max-width: 768px) {
    font-size: 2em;
  }
  &:hover, &:focus {
    color: crimson;
  }
}
```

`Button.jsx`
```jsx
import React from 'react';
import {styled} from 'styletron-react';
import styles from './Button.css';

console.log(JSON.stringify(styles.button, null, 2));

export default styled('button', styles.button);
```

`log output`
```json
{
  "fontSize": "1.5em",
  "color": "fuchsia",
  "@media screen and (max-width: 768px)": {
    "fontSize": "2em"
  },
  ":hover": {
    "color": "crimson"
  },
  ":focus": {
    "color": "crimson"
  }
}
```

**Comment by Xiphe** [comment]
Started implementing it. I'll not use the `sass`-like css syntax as proposed in above but rather plain css. So one can use any preprocessor-loader and then `styletron-loader` instead of [style-loader](https://github.com/webpack-contrib/style-loader).

The above example would stay the same with the following input

```css
.button {
  font-size: 1.5em;
  color: fuchsia;
}
.button:hover,
.button:focus {
  color: crimson;
}
@media screen and (max-width: 768px) {
  .button {
    font-size: 2em;
  }
}
```

I'll also ignore element- and id-selectors unless anybody has a good idea how to treat them.

**Comment by faddee** [comment]
This would be a great initiative! It would help those who wants to migrate from traditional CSS or CSS modules to Styletron. But also gives developers the opportunity to style using CSS instead of Javascript for those who prefer that.

**Comment by Xiphe** [comment]
latest thoughts to element- and id-selectors:

right now I guess, I'll just export the selectors as they are.

So this input:
```css
.foo {
  color: blue;
}
#bar {
  color: red;
}
button {
  color: yellow;
}
```

would be loaded as 

```json
{
  ".foo": {
    "color": "blue"
  },
  "#bar": {
    "color": "red"
  },
  "button": {
    "color": "yellow"
  },
}
```
and could be consumed as

```jsx
import React from 'react';
import {styled} from 'styletron-react';
import styles from './styles.css';

export default styled('p', styles['#bar']);
```
