### ISSUE TITLE
Styles should be prefixed together rather than as individual rulesets

### ISSUE THREAD

**Issue by mattbasta** [rtsao/styletron#142]
Currently, the following will be the case (I've abbreviated the output for simplicity):

Source:
```js
const Foo = styled('div', () => ({display: 'flex'}));
export default () => <Foo />;
```

Output markup:
```html
<div class="a b c"></div>
```

Output CSS:
```css
.a {display: flex}
.b {display: -moz-box}
.c {display: -webkit-box}
```

It should instead include each of the prefixed variants in a single ruleset:

Expected markup:
```html
<div class="a"></div>
```

Expected CSS:
```css
.a {
  display: -moz-box;
  display: -webkit-box;
  display: flex;
}
```

Having individual rulesets for each prefixed variant has a number of downsides:

- Many classnames are consumed to represent a single value, eventually increasing the length of the classnames on each rendered node
- Disabling and adjusting styles at dev time becomes complicated, since many seemingly unrelated rulesets need to be adjusted
- It's theoretically slower to apply each ruleset, since more selectors need to be matched
