### ISSUE TITLE
Handle hydration of content properties containing }

### ISSUE THREAD

**Issue by rtsao** [rtsao/styletron#149]
This is a pretty extreme edge case, but something like:
```css
.a:after{content:"hello } world"}
```
won't be hydrated on the client correctly.
