### ISSUE TITLE
Use 'px' as default units when it's possible

### ISSUE THREAD

**Issue by hssrrw** [rtsao/styletron#35]
Hey, thanks for styletron! I've just started using it and got a proposal.

I'd say, it's expected from CSS-in-JS that when we pass a number as value for a prop which can be in pixels, 'px' would be appended by default.

Currently, if I use a number
```js
import { injectStyle } from 'styletron-utils';
injectStyle(styletron, {
  color: 'red',
  margin: 10,
});
```
the resulting rule is just empty
```css
.a {
  color: red;
}
.b {
}
```
expected:
```css
.b {
  margin: 10px;
}
```

What do you think?
